In [ ]:
pip install tensorflow-macos

In [3]:
import tensorflow as tf
print(tf.__version__)

2.16.2


### Implementing Word Embedding

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
voc_size = 1000
one_hot_repr = [one_hot(word,voc_size) for word in sent]
one_hot_repr

[[597, 85, 708, 352],
 [597, 85, 708, 997],
 [597, 182, 708, 866],
 [390, 477, 939, 705, 740],
 [390, 477, 939, 705, 863],
 [225, 597, 792, 708, 852],
 [993, 862, 791, 705]]

In [4]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [5]:
sent_length = 8
embedding_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedding_docs)

[[  0   0   0   0 597  85 708 352]
 [  0   0   0   0 597  85 708 997]
 [  0   0   0   0 597 182 708 866]
 [  0   0   0 390 477 939 705 740]
 [  0   0   0 390 477 939 705 863]
 [  0   0   0 225 597 792 708 852]
 [  0   0   0   0 993 862 791 705]]


In [6]:
## Feature representation
dim = 10

In [9]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

In [11]:
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │        10,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,000 (39.06 KB)

 Trainable params: 10,000 (39.06 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
predict_docs = model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


In [14]:
embedding_docs[0]

array([  0,   0,   0,   0, 597,  85, 708, 352], dtype=int32)

In [19]:
predict_docs[0][0]

array([-0.03278708, -0.01868473,  0.03140903,  0.0066575 ,  0.01484424,
        0.01340491, -0.03013003, -0.04005558, -0.04998768,  0.01287595],
      dtype=float32)